######################################################################
# Automatically generated by qmake (3.0) So. Mai 21 07:32:19 2017
######################################################################

TEMPLATE = app
TARGET = CircleDetector
INCLUDEPATH += .

# Input
HEADERS += src/CircleDetector.h
SOURCES += src/CircleDetector.cpp src/Main.cpp
QMAKE_CXXFLAGS += -fopenmp
QMAKE_LFLAGS +=  -fopenmp
LIBS += -lgomp -lpthread
